name: Deployment Lab Test

on:
  push:
    branches: [ "deploy__test" ]


jobs:
  print_github_context:
    name: Print GitHub context
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{github}}
          echo ${{github.event_name}}
          echo ${{github.sha}}
          echo ${{github.ref}}
          echo ${{github.workflow}}
          echo ${{github.actor}}
          echo ${{github.repository}}
          echo ${{github.repository_owner}}
          echo ${{github.event}}

      - name: Print GitHub jobs
        env:
          GITHUB_JOBS: ${{ toJson(jobs) }}
        run: |
          echo "$GITHUB_JOBS"
          echo ${{jobs}}
          echo ${{jobs.print_github_context}}
          echo ${{jobs.print_github_context.outputs}}
          echo ${{jobs.print_github_context.outputs.GITHUB_CONTEXT}}
          echo ${{jobs.print_github_context.outputs.GITHUB_CONTEXT.event_name}}
          echo ${{jobs.print_github_context.outputs.GITHUB_CONTEXT.sha}}
          echo ${{jobs.print_github_context.outputs.GITHUB_CONTEXT.ref}}
          echo ${{jobs.print_github_context.outputs.GITHUB_CONTEXT.workflow}}
          echo ${{jobs.print_github_context.outputs.GITHUB_CONTEXT.actor}}
          echo ${{jobs.print_github_context.outputs.GITHUB_CONTEXT.repository}}
          echo ${{jobs.print_github_context.outputs.GITHUB_CONTEXT.repository_owner}}
          echo ${{jobs.print_github_context.outputs.GITHUB_CONTEXT.event}}