name: Deployment Lab Test

on:
  push:
    branches: [ "deploy__test" ]


jobs:
  print_github_context:
    name: Print GitHub context
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{github}}
          echo ${{github.event_name}}
          echo ${{github.sha}}
          echo ${{github.ref}}
          echo ${{github.workflow}}
          echo ${{github.actor}}
          echo ${{github.repository}}
          echo ${{github.repository_owner}}
          echo ${{github.event}}
