# This is a GitHub Actions workflow for testing the deployment of a Docker image to Docker Hub and creating a new release.
name: Deployment Lab Test

# This workflow is triggered when a new tag is pushed.
on:
  push:
    tags:
      - "*"

jobs:
  # This job pushes a Docker image to Docker Hub.
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # This step checks out the repository code.
      - name: Check out the repo
        uses: actions/checkout@v4

      # This step logs into Docker Hub using the provided username and password.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # This step extracts metadata (tags, labels) for the Docker image.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_NAME}}

      # This step builds the Docker image and pushes it to Docker Hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  commit_and_push:
    needs: [ push_to_registry ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push changes
        run: |
          git add .github/workflows/create.release.yml .github/workflows/deployment.lab.yml
          git commit -m "Update workflows"
          git push origin main

      - name: Trigger Release
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ github.repository }}
          event-type: create-release