# This is a GitHub Actions workflow for creating a new release.
name: Create Release

# This workflow is triggered when a new tag is pushed.
on:
  push:
    tags:
      - '*'
jobs:
  build:
    # This job creates a new release.
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      # This step checks out the repository code.
      - name: Checkout code
        uses: actions/checkout@v4

      # This step sets the TAG_NAME environment variable to the name of the latest git tag.
      - name: Set TAG_NAME
        run: echo "TAG_NAME=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      # This step creates a new release using the softprops/action-gh-release action.
      # The new release is created with the name and tag name set to the value of the TAG_NAME environment variable.
      # The release is not a draft or a pre-release.
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false