name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for tag changes
        id: check_tag_changes
        run: |
          echo "Creating release $github"
          git fetch --tags
          PREVIOUS_TAG=$(git describe --tags `git rev-list --tags --skip=1 --max-count=1`)
          CURRENT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ "$PREVIOUS_TAG" != "$CURRENT_TAG" ]; then
            echo "New tag detected, proceeding with the workflow."
          else
            echo "No new tag detected, stopping the workflow."
            exit 1
          fi

      - name: Set TAG_NAME
        run: echo "TAG_NAME=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false